### ISSUE TITLE
could not find .csv file

### ISSUE THREAD

**Issue by dhwani2410** [MitaliBhurani/Scouting-out-urban-areas-from-satellite-imagery#1]
I am new to this kind of analysis. Could you please help me find the .csv file that is used in this analysis.

D:\\Sentinel-2A-2018\\Moradabad\\B(2)_G(3)_R(4)_Nir(8)_stacked_10m\\Sentinel_Data.csv

It is difficult for me to follow the text mentioned below
I used GDAL python package to fetch the raster bands of the composite as arrays and converted the data into CSV file format. However, this is not mandatory and was just done for convenience.

**Could you direct share the link of Sentinel_Data.csv**

**Comment by MitaliBhurani** [comment]
Working with satellite images requires GDAL python package to convert the image into an array. After downloading a satellite image, you should use this package to convert it to array (specifically, reading the image as array). The CSV that I used is confined to my study area and is not to be shared. However, you can use the code to work on your own study area.
